name: release-please
on:
  push:
    branches:
      - master
permissions:
  actions: write
  checks: write
  contents: write
  packages: write
  pull-requests: write
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          command: manifest
          monorepo-tags: true