name: test_issue

on:
  issue_comment:
    types:
      - created
permissions:
  contents: read
  issues: write
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: View issue information
        run: |
          echo "Issue title: ${{ github.event.issue.title }}"
          echo "Issue body: ${{ github.event.issue.body }}"

      # You also can print the whole github context to the logs to view more details.
      - name: View the github context
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
      - uses: actions/github-script@v6
        name: View the issue update
        with:
          script: |
            const result = await github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              state: 'closed'
            })
            console.dir(result)
        if: github.event.comment.user.login == 'NeoHsu' && github.event.comment.body == 'approved'
      - uses: actions/github-script@v6
        name: View the issue create
        with:
          script: |
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'deploy 1234',
              body: '👋 Thanks for reporting!'
            })